### PR TITLE
Replace icon set

### PR DESCRIPTION
**Pull request by seigler**
Replaces old icons with a new icon set (500+ icons in three styles) and a new storybook page to show them.
image

### CODE REVIEW

**Comment by seigler** [comment]
Could maybe also use a completed Docs section with sample code to import and use an icon.

**Review by shadoath — APPROVED** [review]

**Review by slingner — APPROVED** [review]

**Comment by WilliamKelley** [comment]
Could you describe your process of doing this? e.g. using the Figma plugin described here #37, mass file formatting method / tool, etc.

There are a series of things I'd like to revise about this, but knowing your process will help me direct the comments.

**Comment by WilliamKelley** [comment]
@seigler 
Could you describe your process of doing this? e.g. using the Figma plugin described here #37, mass file formatting method / tool, etc.

There are a series of things I'd like to revise about this, but knowing your process will help me direct the comments.

**Comment by WilliamKelley** [comment]
My post-merge review is contained in in #73

**Pull request merged**
