### PR TITLE
feat: simplify dependency narrative

### PR DESCRIPTION
**Pull request by WilliamKelley**
This PR does a lot, sorry. But, it's reviewable by commit, where the most important ones are highlighted in the table below. The rest are housekeeping. Opinionated chores have justification in the commit message details -- open to discussion.

This inadvertently solved our duplicate `ThemeContext` issues. I did not expect that to be the case, but I am so very glad. Turns out importing `ThemeProvider` from not top-level (`@material-ui/core`) will cause the build process to duplicate the context... or something like that, who knew. 

This also cuts bundle size to almost 1/3. Booyah.

Note: "_--_" means that it's the same as the above cell.

Commit | Purpose | umd size | esm size | ThemeContext
---- | ------- | -------- | ------- | ------------
0 | _control_ | 306.55 KB | 280.59 KB | Present
1 | Re-export everything | 307.16 KB | 280.58 KB | _--_
2 | Stories only import from `/src` | _--_ | _--_ | _--_
3 | Components only import from `@material-ui/core` | 112.22 KB | 106.28 KB | **Absent**
... | _chores_ | _--_ | _--_ | _--_
11 | actually type NavBarButton's props | 112.1 KB | 106.2 KB | _--_
12 | remove `styled-components` usage and peer-dep | 111.31 KB | 105.22 KB | _--_

### CODE REVIEW

**Comment by WilliamKelley** [comment]
Closes #167
Closes #156
Closes #67
Closes #46

**Review by shadoath — APPROVED** [review]
Big changes. Nice work. I think the small bundle is a big improvement plus gave me more understanding of theme context and tree shaking reading this PR.

I noticed icons no longer export with the `...Icon` ending. Didn't see that mentioned in the commits or issues. Will that be the case for all icons in Prenda spark?

**Comment by WilliamKelley** [comment]
> I noticed icons no longer export with the `...Icon` ending. Didn't see that mentioned in the commits or issues. Will that be the case for all icons in Prenda spark?

The pattern was established in the icon library PR series. Consumers go to Figma Icons File > Page Name (Line, Filled, Duotone) > Select icon to read component name. Imports follow the pattern:
- Line variant -> `Name`
- Filled variant -> `NameFilled`
- Duotone variant -> `NameDuotone`

No "Icon" suffix. Main reasoning being that it makes the names shorter (convenience and smaller bundle size over 1000s of instances), it's the standard among other icon libraries (mui icons, font-awesome), and consumers can always rename the named import or write any custom name for the default import. 

I changed all of our internal uses just to simplify things and establish one internal narrative.

**Review by seigler — APPROVED** [review]
Good PR is good.

**Pull request merged**
