### PR TITLE
chore(release): 0.9.0

### PR DESCRIPTION
**Pull request by WilliamKelley**
Had to do some heavy revision on the changelogs, see the second commit.

The plugin was actually failing me for some reason, it would always try to bump from v0.8.0 to v0.8.0
```bash
✔ bumping version in /home/william/projects/spark/libs/spark/package.json from 0.8.0 to 0.8.0
✔ bumping version in /home/william/projects/spark/package.json from 0.8.0 to 0.8.0
✔ bumping version in /home/william/projects/spark/libs/spark-icons/package.json from 0.0.1 to 0.8.0
# ... and so on, failing at
✔ tagging release v0.8.0
fatal: tag 'v0.8.0' already exists

Command failed: git tag -a v0.8.0 -m chore(release): 0.8.0
fatal: tag 'v0.8.0' already exists
```
So I had to manually tag with 0.9.0, manual commit, manually change the initial changelog generation of tag comparison links.

Maybe it was because it was our first actual version bump with spark-icons that had a different version from spark. Hopefully doesn't happen in the future.

### CODE REVIEW

**Comment by WilliamKelley** [comment]
Looks like it missed `NavBar` and `NavBarButton`. Not sure why. But, I'll go back and add those

**Comment by WilliamKelley** [comment]
It also looks like no "BREAKING CHANGE" type information is being picked up by the tool for inclusion in the changelogs... That's a bummer. Not sure how to best go back and manually revise that.

**Comment by WilliamKelley** [comment]
Went through the commit history and old version compares to add missed PR commits and breaking changes summary.

**Review by seigler — APPROVED** [review]
:confetti_ball:

**Review by slingner — APPROVED** [review]

**Pull request merged**
