### PR TITLE
feat(spark-icons): add all icons

### LINKED ISSUE #73: Separate `@prenda/spark-icons`, revise generation method
Given that #68 introduced ~1700 icon files, we need to be very specific and careful about how we're defining and exporting them.

### Problems

- The 1700 files take up ~2.41 MB of raw space, and even more on a user's disk depending on their disk file format (see below).
  - This enormous file count and overall size can bring bundlers to a literal crawl if the library isn't correctly tree-shakable / or icons aren't otherwise directly importable -- I have a feeling that with all the problems consumers have had, our library currently falls under this category.
- Current directory layout prevents consumer from specifying the same [import transform plugin rule](https://material-ui.com/guides/minimizing-bundle-size/#option-2) that MUI advises.
- Icon svg files are not optimized and contain unneeded accessory info.

image

### Solution

- Create new package `@prenda/spark-icons` -- overall this will mirror [`@material-ui/icons`](https://github.com/mui-org/material-ui/tree/latest/packages/material-ui-icons)
- Locate all icons in top-level of `src/`
  - Mimic [MUI's naming scheme](https://material-ui.com/components/icons/#usage)
```bash
src
├── Activity.tsx # Line variant, default (no suffix)
├── ActivityFilled.tsx # Filled variant
├── ActivityDuotone.tsx # Duotone variant
```
- After bulk export from Figma, create a script with [SVGO](https://github.com/svg/svgo) that's similar to [MUI's script](https://github.com/mui-org/material-ui/blob/latest/packages/material-ui-icons/builder.js) to rename and optimize the `path` tags of the SVG. 
  - The optimized output ideally is: 
    - 1 path tag per icon (duotone maybe requires 2)
    - one `d` attribute per tag (`fillRule`, `clipRule` might be unavoidable by just using SVGO though, that'd be fine).
    - completely get rid of `svg` tag definition, the `SvgIcon` component takes care of this for us.
  - File mimics [MUI's layout](https://github.com/mui-org/material-ui/blob/latest/packages/material-ui-icons/src/AcUnit.js)
    - Copy their [internal `createSvgIcon` util](https://github.com/mui-org/material-ui/blob/42954448866f204b0cf7e35127d5d0af9c24d6fb/packages/material-ui/src/utils/createSvgIcon.js#L7) to our codebase

### PR DESCRIPTION
**Pull request by WilliamKelley**
## 4 of 4

Closes #73. Reviewable by commit.

1. Project generation (#132)
2. Copying of icon utility scripts from Mui & Modification for our use case (#133)
3. Removal of icons from @prenda/spark & Specific generation and replacement of depended-on icons (#134)
4. **Addition of all icons in @prenda/spark-icons (this PR)**

### Addition
All 1688 icon files were generated and added, in addition to the 9 existing files

### Building
The library is buildable, which is great. There's an error about `templateSvgIcon.tsx` not being under `src/`. The build generates a typing file for it. I would like to have it just be excluded from the build process, but I don't know how to specify that.
```bash
> nx run spark-icons:build 
Bundling spark-icons...
rpt2: options error TS6059: File '/home/william/projects/spark/libs/spark-icons/defaults/templateSvgIcon.tsx' is not under 'rootDir' '/home/william/projects/spark/libs/spark-icons/src'. 'rootDir' is expected to contain all source files.
'elementType' is not exported by 'node_modules/prop-types/index.js'
No name was provided for external module 'react-is' in output.globals – guessing 'reactIs'
┌────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                        │
│   Destination: /home/william/projects/spark/dist/libs/spark-icons/spark-icons.umd.js   │
│   Bundle Size:  2.51 MB                                                                │
│   Minified Size:  2.21 MB                                                              │
│   Gzipped Size:  391.99 KB                                                             │
│                                                                                        │
└────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: spark-icons
rpt2: options error TS6059: File '/home/william/projects/spark/libs/spark-icons/defaults/templateSvgIcon.tsx' is not under 'rootDir' '/home/william/projects/spark/libs/spark-icons/src'. 'rootDir' is expected to contain all source files.
'elementType' is not exported by 'node_modules/prop-types/index.js'
┌────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                        │
│   Destination: /home/william/projects/spark/dist/libs/spark-icons/spark-icons.esm.js   │
│   Bundle Size:  2.47 MB                                                                │
│   Minified Size:  2.28 MB                                                              │
│   Gzipped Size:  395.78 KB                                                             │
│                                                                                        │
└────────────────────────────────────────────────────────────────────────────────────────┘
Bundle complete: spark-icons

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build" succeeded
```

### CODE REVIEW

**Review by seigler — APPROVED** [review]
Splendid.
How can we showcase the icons or make them searchable for devs without sending them to Figma? Is that a feasible thing to do in Storybook?

**Comment by WilliamKelley** [comment]
@seigler I'm tracking that issue in #106. We'd have to static host them somewhere, and have the Storybook issue queries for svg files.

Currently I think it's acceptable that they go into Spark's Figma file for Icons. There's a reasonable name transformation for any icon:

'Name' 
-> 'Name' (Line page)
-> 'NameFilled' (Filled page)
-> 'NameDuotone' (Duotone page)

**Comment by seigler** [comment]
image

**Review by shadoath — APPROVED** [review]

**Comment by WilliamKelley** [comment]
Merging this without Chromatic UI Review / Tests because I can verify it adds only new component files with no associated stories.

**Pull request merged**
