### PR TITLE
feat(CheckboxGroup): initial implementation (**not a component, just a pattern)

### LINKED ISSUE #40: Checkbox Control defaulting to MUI secondary color
When using the Spark checkbox:

Code example:

```
<Checkbox
  checked={microschoolProfile.grades.indexOf(grade) > -1}
  control={<Checkbox />}
  label={grade}
 />
```

The component works fine but if a the checkbox is unchecked, it defaults to the default MUI checkbox, specifically the secondary default color. 

Screen Shot 2021-05-18 at 12 52 23 PM

### LINKED ISSUE #66: Group for Radio, Checkbox
Result of #42. Should address #40.

As noted in #40, this should involve breaking the FormControlLabel out of the current Radio and Checkbox, and allowing a more verbose but composable pattern so the Control's of Radio and Checkbox can be passed RadioGroup and such.

### PR DESCRIPTION
**Pull request by WilliamKelley**
Includes #114 -- last two commits are relevant

Closes #40 and Closes #66

Validates styling support for a pattern that's essential "CheckboxGroup", but that component doesn't actually exist. It exists for `RadioGroup` because that ensures only one value is `checked` across many `Radio`'s, but it's not the case for `Checkbox`'s because many can be checked. Thus it exposes the underlying component `FormGroup`. This is Mui's recommended pattern.

Adds story groups as well.

### CODE REVIEW

**Comment by seigler** [comment]
We may have to examine how our code samples are generated at some point. It's not quite relevant to this PR, which looks great.
image

**Review by seigler — APPROVED** [review]

**Comment by WilliamKelley** [comment]
@seigler Yeah I noticed that as well, will keep it in mind

**Review by shadoath — APPROVED** [review]
Gosh, get behind in reviewing all of these and the changes stack up!

**Comment by WilliamKelley** [comment]
> 
> 
> Gosh, get behind in reviewing all of these and the changes stack up!

Yeah sorry about that, I know that's a pain. These series of PR's were highly related and needed changes made in each other, so they got quite messy unfortunately.

**Pull request merged**
